import { StyleSheet } from 'react-native'
import {
  mainColor,
  FONT_SIZE_12,
  INDENT_14,
  INDENT_12,
  lightGreyColor,
  WINDOW_WIDTH,
  whiteColor,
  INDENT_20,
  INDENT_35,
  INDENT_5,
  semiTransparentBackground,
  LINE_HEIGHT_24,
  greyColor,
  FONT_SIZE_14,
  INDENT_8,
  INDENT_16,
  FONT_WEIGHT_BOLD,
  secondaryColor,
} from '../../theme'

export const styles = StyleSheet.create({
  buttonContainer: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: whiteColor,
    borderRadius: 15,
    elevation: 5,
    height: INDENT_35,
    marginTop: INDENT_16,
    paddingHorizontal: INDENT_16,
    paddingVertical: INDENT_8,
    shadowColor: mainColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  buttonTitle: {
    color: mainColor,
    fontSize: FONT_SIZE_12,
    marginLeft: INDENT_12,
  },
  cancelButtonBlock: {
    alignSelf: 'center',
    backgroundColor: lightGreyColor,
    borderRadius: 22,
    height: 43,
    marginTop: 20,
  },
  centeredView: {
    alignItems: 'center',
    backgroundColor: semiTransparentBackground,
    flex: 1,
    justifyContent: 'center',
  },
  container: {
    flexDirection: 'row',
    paddingHorizontal: INDENT_14,
    paddingVertical: INDENT_14,
    width: WINDOW_WIDTH,
  },
  disclamer: {
    color: greyColor,
    fontSize: FONT_SIZE_14,
    lineHeight: LINE_HEIGHT_24,
  },
  enterButton: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
  },
  enterButtonBlock: {
    alignSelf: 'center',
    backgroundColor: secondaryColor,
    borderRadius: 22,
    height: 43,
    marginTop: 20,
  },
  enterButtonText: {
    color: whiteColor,
    fontSize: FONT_SIZE_14,
    fontWeight: FONT_WEIGHT_BOLD,
  },
  iconButtonContainer: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: whiteColor,
    borderRadius: 15,
    elevation: 5,
    flexDirection: 'row',
    height: INDENT_35,
    marginTop: INDENT_16,
    paddingHorizontal: INDENT_16,
    paddingVertical: INDENT_8,
    shadowColor: mainColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  imageControls: {
    flexDirection: 'row',
  },
  imagePreview: {
    height: 130,
    marginRight: 14,
    width: 130,
  },
  imagePreviewImage: { borderRadius: 55 },
  modalView: {
    backgroundColor: whiteColor,
    borderRadius: INDENT_20,
    elevation: INDENT_5,
    margin: INDENT_20,
    padding: INDENT_35,
    shadowColor: mainColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  sideBlock: {
    flex: 1,
    marginLeft: INDENT_14,
  },
})
